<?php
if (!isset($_REQUEST["Project"]))
{
	http_response_code(400);
	exit();
}
if (!is_dir("../../Share/".$_REQUEST["Project"]))
{
	http_response_code(400);
	exit();
}
$ID = $_REQUEST["Project"];
$files = array();


if (!is_dir("../../Share/".$ID."/sounds/"))
	mkdir("../../Share/".$ID."/sounds/", 0777, true);


if ($handle = opendir("../../Share/".$ID."/sounds/")) {
    while (false !== ($entry = readdir($handle))) {
        if ($entry != "." && $entry != "..") {
            $files[] = str_replace(".wav", "", $entry);
        }
    }
    closedir($handle);
}
$json = json_encode($files);
$json = json_decode($json,true);
if(is_file("../../Share/".$ID."/Audio.js")) {
	unlink("../../Share/".$ID."/Audio.js");
}
$Audio = fopen("../../Share/".$ID."/Audio.js", "c");
fwrite($Audio, "// File is automaticly Generated By GetAudio.php\n");
foreach ($json as $item) 
{
	fwrite($Audio,$item.' = new Audio("../../Share/'.$ID.'/sounds/'.$item.'.wav")');
	fwrite($Audio,"\n");
}
fwrite($Audio, "function audio_stopall()\n{");
	fwrite($Audio,"\n");
	foreach ($json as $item) {
		fwrite($Audio, "\t".$item.'.currentTime=0;');
		fwrite($Audio,"\n");
		fwrite($Audio, "\t".$item.'.pause();');
		fwrite($Audio,"\n");
	}
	fwrite($Audio, "}");
	fwrite($Audio,"\n\n");
fwrite($Audio,"var \$builtinmodule = function (name)\n{");
fwrite($Audio,"\n");
fwrite($Audio,"\tmod={}\n");

foreach ($json as $item) {
	fwrite($Audio, "\n\t".'mod["'.$item.'"] = new Sk.builtin.func(function () {return "SoundObject"});');
	fwrite($Audio,"\n");
	fwrite($Audio, "\t".'mod["'.$item.'"].play = new Sk.builtin.func(function () {'.$item.'.play()});');
	fwrite($Audio,"\t"."\n");
	fwrite($Audio, "\t".'mod["'.$item.'"].stop = new Sk.builtin.func(function () {'.$item.'.currentTime=0, '.$item.'.pause()});');
	fwrite($Audio,"\n");
	fwrite($Audio, "\t".'mod["'.$item.'"].pause = new Sk.builtin.func(function () {'.$item.'.pause()});');
	fwrite($Audio,"\n");
}

fwrite($Audio,"\t".'return mod;');
fwrite($Audio,"\n");
fwrite($Audio,"}");
fclose($Audio);
